### ISSUE TITLE
PDF rendered with completely incorrect colors

### ISSUE THREAD

**Issue by Etienne-Gautier** [Etienne-Gautier/pdfbox#1]
Repro document (flat PDF containing 1 image per page):
[uae-visa-application-form-english.pdf](https://github.com/Etienne-Gautier/pdfbox/files/12911762/uae-visa-application-form-english.pdf)

In pdfbox debugger-app:
<img width="1708" alt="Screenshot 2023-10-16 at 2 29 19 pm" src="https://github.com/Etienne-Gautier/pdfbox/assets/25138293/d1ca85a5-3ccd-4630-b49c-0b6da435ca2c">

In Acrobat:
<img width="1346" alt="Screenshot 2023-10-16 at 2 30 11 pm" src="https://github.com/Etienne-Gautier/pdfbox/assets/25138293/8ebda946-72c3-4032-a875-ed5ea006aefc">

**Comment by THausherr** [comment]
Possibly a bug in twelvemonkeys plugin. If you weren't using it (you should), then I assume it is a bug in java as well.

**Comment by Etienne-Gautier** [comment]
I was using JAI's implementation of imageIO, but will look into twelvemonkeys. Thanks for having a look and filing that bug

**Comment by Etienne-Gautier** [comment]
Closing issue, it looks like it was fixed in twelvemonkeys, will be interested in the new release. JAI also has the bug, but it is no longer actively maintained so I won't bother raising that

**Comment by THausherr** [comment]
It turns out PDFBox will have to change some code as well.
https://issues.apache.org/jira/browse/PDFBOX-5706
